Vshilin patch 3 fixing ad/kerberos sso article
exasol/public-knowledgebase pull request #106
Opened 2024-12-19 18:00 UTC by vshilin

I've updated the article about Kerbersos AD SSO according to the newly found issues. Please review.

2024-12-19 22:32 UTC, allipatev commented
Will be happy to review when I'm back.

2025-01-06 13:37 UTC, allipatev requested changes
Changes look good!

I added some cosmetic suggestions a two questions.

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* Start up the database using [db_start](https://docs.exasol.com/db/latest/confd/jobs/db_start.htm) confd job.
```suggestion
* Start up the database using [db_start](https://docs.exasol.com/db/latest/confd/jobs/db_start.htm) ConfD job.
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +  *  **\{Kerberos realm\}**: In AD it is usually the domain name written in all capital letters. The AD usre must have the same Realm as the Exasol service account from Step 1.
```suggestion
  *  **\{Kerberos realm\}**: In AD it is usually the domain name written in all capital letters. The AD user must have the same Realm as the Exasol service account from Step 1.  
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* To verify network connectivity between the client machine and the Exasol database, first attempt to connect to the database using a standard authentication method with a username and password. For
Did we create a dba user in Step 6?

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +`Error: [28900] Cannot initialize SSPI security context. The specified target is unknown or unreachable` during Step 7. This usually mean that prived parameters **Service name** and **Host** don't ma
```suggestion
`Error: [28900] Cannot initialize SSPI security context. The specified target is unknown or unreachable` during Step 7. This usually mean that provided parameters **Service name** and **Host** don't match the service keytab uploaded in Exasol DB.
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* Make sure that **Service name** and **Host** are exactly the same as returned by `setspn -L {Service account name}` command. Run it in the same command promt before runing Exaplus.
```suggestion
* Make sure that **Service name** and **Host** are exactly the same as returned by `setspn -L {Service account name}` command. Run it in the same command prompt before running Exaplus.
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* Permissions on `/var/tmp/krb5_500.rcache2`.There might be an issue with permissions for this file `/var/tmp/krb5_500.rcache2`. It is a temporary file used by the Kerberos authentication mechanism t
```suggestion
* Permissions on `/var/tmp/krb5_500.rcache2`.There might be an issue with permissions for this file `/var/tmp/krb5_500.rcache2`. It is a temporary file used by the Kerberos authentication mechanism to store information about authentication tickets that have been issued. This file is generated by the Kerberos libraries when Exasol performs Kerberos authentication. Ensure that users in the `exausers` group (in particular this user: `exadefusr` ) have Read/Write permissions in the `/var/tmp/` directory on all nodes. If permissions are insufficient, issue corresponding chmod command: `chmod 777 /var/tmp/`
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* Check that **Kerberos Realm** db parameter is correctly set in Exaoperation/EXAConf.
```suggestion
* Check that **Kerberos Realm** db parameter is correctly set in EXAoperation/EXAConf.
```

2025-01-06 13:37 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* This error could indicate several different issues. To investigate further, export the database logs following the [instructions here](https://docs.exasol.com/db/latest/administration/on-premise/ad
1.
```suggestion
* This error could indicate several different issues. To investigate further, export the database logs following the [instructions here](https://docs.exasol.com/db/latest/administration/on-premise/admin_interface/exasupport.htm) and send them to Exasol Support.
```

2. The article covers both version 7.1 with EXAoperation and version 8. Maybe we can also include a link for 7.1?

2025-01-10 08:36 UTC, vshilin commented on Database-Features/setting-up-ad-kerberos-sso.md
> +* To verify network connectivity between the client machine and the Exasol database, first attempt to connect to the database using a standard authentication method with a username and password. For
No, here we have to use another user - just some user that could be authenticated with username and pass. In step 6 we create a specific user authenticated by kerberos principal.
Here just refer to some dba user.

2025-01-10 08:58 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +To successfully set up and use this integration, ensure the following requirements are met:
```suggestion
To successfully set up and use this int  egration, ensure the following requirements are met:
```

2025-01-10 08:58 UTC, allipatev commented on Database-Features/setting-up-ad-kerberos-sso.md
> +- Installed and configured to authenticate users.
```suggestion
- Installed and configured to authe  nticate users.
```

2025-01-10 09:00 UTC, allipatev approved these changes

2025-01-10 09:02 UTC, merged