Updated readme
exasol/Public-Knowledgebase pull request #14
Opened 2022-11-14 19:15 UTC by susanbuckley

Took out KB article

2022-11-15 14:22 UTC, nconforti93 commented
@susanbuckley  I suggest to create a doc folder and put the style guide in there as well as the templates. I think it's important that the README mentions the overall layout of the repo, how to contribute and work with it, where to find further information, and any restrictions to keep in mind. Adding the very detailed style guide on this level might make it difficult for people to see just how to use it in general

2022-11-15 14:23 UTC, nconforti93 requested changes

2022-11-15 14:24 UTC, nconforti93 commented
Of course, if this isn't necessary you think then we just need to restructure the readme a bit

2022-11-15 14:34 UTC, susanbuckley commented
Per one of the Readme or both I thought only you could create

Get Outlook for Android<https://aka.ms/AAb9ysg>

Exasol INC.
Susan Buckley | Technical Writer


***@***.******@***.***>
www.exasol.com<http://www.exasol.com/en/>

Get the latest news:
www.exasol.com/newsroom/<http://www.exasol.com/en/company/newsroom/>

[cid:sign_1-Main_b6957fc3-66b6-468b-b929-70b78e51ebab.png]<https://www.linkedin.com/company/exasol-ag/>[cid:sign_2_twitter_e3a8df5e-6f92-4546-97f2-cfae237d9dae.png]<https://twitter.com/ExasolAG>[cid:sign_3_linkedin_df799929-e125-45ad-afa8-1522692489e1.png]<https://www.linkedin.com/company/exasol-ag/><https://twitter.com/ExasolAG><https://www.xing.com/company/exasol><https://www.linkedin.com/company/exasol-ag/>

This e-mail may contain confidential information. If you are not the intended recipient please notify the sender immediately. Any unauthorised
copying or distribution of this e-mail is forbidden.

________________________________
From: Nico Conforti ***@***.***>
Sent: Tuesday, November 15, 2022 6:24:19 AM
To: exasol/Public-Knowledgebase ***@***.***>
Cc: Susan Buckley ***@***.***>; Mention ***@***.***>
Subject: Re: [exasol/Public-Knowledgebase] Updated readme (PR #14)


Of course, if this isn't necessary you think then we just need to restructure the readme a bit

—
Reply to this email directly, view it on GitHub<https://github.com/exasol/Public-Knowledgebase/pull/14#issuecomment-1315381752>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUU5GY6ZMBURWMZ5TPKA3Q3WIOMJHANCNFSM6AAAAAASAEYRRU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-15 20:08 UTC, susanbuckley commented on README.md
> +Welcome to the Exasol Knowledgebase! This repository contains source files for Exasol's knowledgebase. The files in this repository are used to create the Knowledgebase, which is accessible at [Exaso
Made changes per our meeting this morning.

2022-11-15 20:08 UTC, susanbuckley commented on README.md
>  If you wish to contribute to the knowledgebase, feel free to fork the repository and make a pull request with your changes.
Made changes per our meeting this morning.

2022-11-16 14:48 UTC, susanbuckley commented
@nconforti93 I believe I've made the needed changes and resolved the conflict.

2022-11-18 21:18 UTC, nconforti93 approved these changes
approved

2022-11-18 21:18 UTC, merged